CREATE TABLE IF NOT EXISTS components (
  id TEXT PRIMARY KEY,
  "desc" TEXT NOT NULL DEFAULT '',
  component_type TEXT DEFAULT '',
  oe_export TEXT DEFAULT '',
  material_discipline TEXT DEFAULT '',
  cat TEXT DEFAULT '',
  product_group TEXT DEFAULT '',
  uom TEXT DEFAULT '',
  buyer TEXT DEFAULT '',
  supplier TEXT DEFAULT '',
  vendor TEXT DEFAULT '',
  vendor_code TEXT DEFAULT '',
  mpn TEXT DEFAULT '',
  make TEXT DEFAULT '',
  spq DOUBLE PRECISION DEFAULT 0,
  moq DOUBLE PRECISION DEFAULT 0,
  lead_time_weeks DOUBLE PRECISION DEFAULT 0,
  rate DOUBLE PRECISION DEFAULT 0,
  open_balance DOUBLE PRECISION DEFAULT 0,
  store_stock_mm01 DOUBLE PRECISION DEFAULT 0,
  inspection_stock DOUBLE PRECISION DEFAULT 0,
  store_stock_mm10 DOUBLE PRECISION DEFAULT 0,
  wip_stock DOUBLE PRECISION DEFAULT 0,
  qr01_stock DOUBLE PRECISION DEFAULT 0,
  ib_pending DOUBLE PRECISION DEFAULT 0,
  inward_qty DOUBLE PRECISION DEFAULT 0,
  eta TEXT DEFAULT '',
  stock DOUBLE PRECISION DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fg_products (
  part_no TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  "desc" TEXT DEFAULT '',
  buyer TEXT DEFAULT '',
  customer TEXT DEFAULT '',
  market_segment TEXT DEFAULT '',
  product_group TEXT DEFAULT '',
  product_type TEXT DEFAULT '',
  customer_category TEXT DEFAULT '',
  stock_norm_days DOUBLE PRECISION DEFAULT 0,
  total_stock DOUBLE PRECISION DEFAULT 0,
  fg_category TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS fg_stock_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  monitor_date TEXT NOT NULL,
  fg_part_no TEXT NOT NULL REFERENCES fg_products(part_no) ON DELETE CASCADE,
  month_key TEXT DEFAULT '',
  month_plan_qty DOUBLE PRECISION DEFAULT 0,
  adr DOUBLE PRECISION DEFAULT 0,
  stock_norm_days DOUBLE PRECISION DEFAULT 0,
  total_stock DOUBLE PRECISION DEFAULT 0,
  UNIQUE (monitor_date, fg_part_no)
);
CREATE TABLE IF NOT EXISTS working_days_calendar (
  month_key TEXT PRIMARY KEY,
  working_days INTEGER NOT NULL DEFAULT 24,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fg_bom_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fg_part_no TEXT NOT NULL REFERENCES fg_products(part_no) ON DELETE CASCADE,
  component_id TEXT NOT NULL REFERENCES components(id),
  norms DOUBLE PRECISION NOT NULL DEFAULT 0,
  UNIQUE (fg_part_no, component_id)
);

CREATE TABLE IF NOT EXISTS fg_monthly_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fg_part_no TEXT NOT NULL REFERENCES fg_products(part_no) ON DELETE CASCADE,
  month_key TEXT NOT NULL,
  qty DOUBLE PRECISION DEFAULT 0,
  UNIQUE (fg_part_no, month_key)
);

CREATE TABLE IF NOT EXISTS production_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fg_part_no TEXT NOT NULL REFERENCES fg_products(part_no),
  qty DOUBLE PRECISION NOT NULL,
  production_date DATE NOT NULL,
  bom_id TEXT DEFAULT '',
  bom_name TEXT DEFAULT '',
  bom_description TEXT DEFAULT '',
  priority_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS production_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fg_part_no TEXT NOT NULL,
  fg_name TEXT DEFAULT '',
  qty DOUBLE PRECISION NOT NULL,
  run_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  bom_id TEXT DEFAULT '',
  bom_name TEXT DEFAULT '',
  bom_description TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS production_run_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES production_runs(id) ON DELETE CASCADE,
  component_id TEXT NOT NULL,
  norms DOUBLE PRECISION DEFAULT 0,
  required DOUBLE PRECISION DEFAULT 0,
  stock_before DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS stock_movements (
  id TEXT PRIMARY KEY,
  transaction_id TEXT DEFAULT '',
  type TEXT NOT NULL,
  component_id TEXT NOT NULL,
  component_desc TEXT DEFAULT '',
  qty DOUBLE PRECISION DEFAULT 0,
  before_stock DOUBLE PRECISION,
  after_stock DOUBLE PRECISION,
  bucket TEXT DEFAULT '',
  vendor TEXT DEFAULT '',
  invoice_no TEXT DEFAULT '',
  receipt_date DATE,
  remarks TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor TEXT NOT NULL DEFAULT 'system',
  role TEXT DEFAULT '',
  action TEXT NOT NULL,
  entity TEXT DEFAULT '',
  detail TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_bom_fg ON fg_bom_items(fg_part_no);
CREATE INDEX IF NOT EXISTS idx_bom_component ON fg_bom_items(component_id);
CREATE INDEX IF NOT EXISTS idx_prod_plan_date ON production_plans(production_date);
CREATE INDEX IF NOT EXISTS idx_prod_plan_fg ON production_plans(fg_part_no);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at);
