import {
  getAllComponents,
  getAllFgProducts,
  getAllProductionPlans,
  getAllProductionRuns,
  getAllStockMovements,
  getEmailRecipients,
  getEmailSettings,
  createEmailReportLog,
  hasSuccessfulEmailReport,
} from './repository.js';
import { buildComponentMetrics } from './calculations.js';
import { getMonthKeyFromDate } from './workingDays.js';

const DEFAULT_SEND_TIME = '17:30';
const pad = (value) => String(value).padStart(2, '0');
const localDateKey = (date = new Date()) => `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
const fmt = (value) => Number(value || 0).toLocaleString('en-IN');

function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
}

function getDailyDigestData(dateKey = localDateKey()) {
  const components = getAllComponents();
  const products = getAllFgProducts();
  const runs = getAllProductionRuns().filter((run) => localDateKey(new Date(run.date)) === dateKey);
  const movements = getAllStockMovements().filter((movement) =>
    ['INWARD', 'BULK_UPDATE'].includes(movement.type) &&
    (movement.receiptDate || localDateKey(new Date(movement.createdAt))) === dateKey,
  );
  const critical = buildComponentMetrics(
    components,
    products,
    getAllProductionRuns(),
    getAllProductionPlans(),
    getMonthKeyFromDate(dateKey),
  ).filter((row) => row.risk === 'critical');
  return { dateKey, runs, movements, critical };
}

function table(headers, rows, emptyText) {
  const head = headers.map((header) => `<th style="padding:8px;text-align:left;border-bottom:1px solid #cbd5e1">${escapeHtml(header)}</th>`).join('');
  const body = rows.length
    ? rows.map((row) => `<tr>${row.map((cell) => `<td style="padding:8px;border-bottom:1px solid #e2e8f0">${escapeHtml(cell)}</td>`).join('')}</tr>`).join('')
    : `<tr><td colspan="${headers.length}" style="padding:16px;color:#64748b">${escapeHtml(emptyText)}</td></tr>`;
  return `<table cellpadding="0" cellspacing="0" style="border-collapse:collapse;width:100%;font-size:12px"><thead style="background:#eff6ff;color:#1e3a8a"><tr>${head}</tr></thead><tbody>${body}</tbody></table>`;
}

function buildDailyDigestHtml({ dateKey, runs, movements, critical }) {
  const inwardTotal = movements.reduce((sum, row) => sum + Number(row.qty || 0), 0);
  const productionTotal = runs.reduce((sum, row) => sum + Number(row.qty || 0), 0);
  return `<div style="font-family:Arial,sans-serif;color:#0f172a;max-width:1100px;margin:auto">
    <div style="background:#17243d;color:white;padding:22px 26px;border-radius:10px 10px 0 0"><h2 style="margin:0">INEL RM — Evening Operations Digest</h2><p style="margin:6px 0 0;color:#cbd5e1">Unit 2 · ${escapeHtml(dateKey)}</p></div>
    <div style="display:flex;gap:12px;padding:18px;background:#f8fafc">
      <div style="flex:1;background:white;padding:14px;border:1px solid #e2e8f0"><small>STOCK INWARD LINES</small><b style="display:block;font-size:22px;margin-top:5px">${movements.length}</b><span style="font-size:11px;color:#64748b">Qty ${fmt(inwardTotal)}</span></div>
      <div style="flex:1;background:white;padding:14px;border:1px solid #e2e8f0"><small>PRODUCTION CONFIRMED</small><b style="display:block;font-size:22px;margin-top:5px">${runs.length}</b><span style="font-size:11px;color:#64748b">FG Qty ${fmt(productionTotal)}</span></div>
      <div style="flex:1;background:white;padding:14px;border:1px solid #e2e8f0"><small>CRITICAL COMPONENTS</small><b style="display:block;font-size:22px;margin-top:5px;color:#dc2626">${critical.length}</b><span style="font-size:11px;color:#64748b">Current position</span></div>
    </div>
    <h3 style="margin:22px 0 8px">Today's Stock Inward</h3>${table(['Receipt/Batch','Material','Description','Qty','Vendor','Invoice'], movements.map(m=>[m.transactionId||m.id,m.componentId,m.componentDesc,fmt(m.qty),m.vendor||'-',m.invoiceNo||'-']), 'No stock inward recorded today.')}
    <h3 style="margin:22px 0 8px">Today's Confirmed BOM / Production</h3>${table(['Run ID','Confirmed Time','FG Part','FG Name','FG Qty','Components'], runs.map(r=>[`PRD-${String(r.id).padStart(6,'0')}`,new Date(r.date).toLocaleTimeString('en-IN'),r.partNo,r.name,fmt(r.qty),(r.items||[]).length]), 'No production confirmations recorded today.')}
    <h3 style="margin:22px 0 8px">Current Critical Components</h3>${table(['Component','Description','Vendor','Stock','Required','Shortage','Coverage'], critical.map(r=>[r.id,r.desc,r.vendor||'-',fmt(r.totalStock),fmt(r.demandRequirement),fmt(r.shortage),r.coverageDays??'-']), 'No critical components.')}
    <p style="margin-top:22px;color:#94a3b8;font-size:11px">Automatically generated by INEL RM at the configured evening schedule.</p>
  </div>`;
}

function getSmtpConfig() {
  return {
    host: process.env.SMTP_HOST,
    port: Number(process.env.SMTP_PORT || 587),
    secure: String(process.env.SMTP_SECURE || '').toLowerCase() === 'true',
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
    from: process.env.SMTP_FROM || process.env.SMTP_USER,
  };
}

export async function sendRiskEmailNow() {
  const config = getSmtpConfig();

  if (!config.host || !config.from) {
    throw new Error(
      'SMTP not configured. Set SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS and SMTP_FROM.'
    );
  }

  const recipients = getEmailRecipients()
    .filter((recipient) => recipient.enabled)
    .map((recipient) => recipient.email);

  if (!recipients.length) {
    throw new Error(
      'No enabled email recipients found. Add at least one enabled recipient.'
    );
  }

  const nodemailer = await import('nodemailer').catch(() => null);

  if (!nodemailer) {
    throw new Error('nodemailer is not installed.');
  }

  const digest = getDailyDigestData();

  const transporter = nodemailer.default.createTransport({
    host: config.host,
    port: config.port,
    secure: config.secure,
    auth:
      config.user && config.pass
        ? {
            user: config.user,
            pass: config.pass,
          }
        : undefined,
  });

  try {
    await transporter.sendMail({
      from: config.from,
      to: recipients,
      subject: `INEL RM Evening Digest - ${digest.dateKey}`,
      html: buildDailyDigestHtml(digest),
    });

    createEmailReportLog({
      reportDate: digest.dateKey,
      sentAt: new Date().toISOString(),
      status: 'SENT',
      recipientCount: recipients.length,
    });

    return {
      sent: true,
      recipientCount: recipients.length,
      itemCount: digest.critical.length,
      stockInwardCount: digest.movements.length,
      productionCount: digest.runs.length,
      date: digest.dateKey,
    };
  } catch (error) {
    createEmailReportLog({
      reportDate: digest.dateKey,
      sentAt: null,
      status: 'FAILED',
      recipientCount: recipients.length,
      errorMessage: error.message,
    });

    throw error;
  }
}

export function startDailyRiskEmailJob() {
  let lastSentDate = '';
  let sending = false;

  const checkAndSend = async () => {
    const settings = getEmailSettings();

    // Daily email feature disabled
    if (!settings.enabled) return;

    const now = new Date();
    const today = localDateKey(now);
    const hhmm = `${pad(now.getHours())}:${pad(now.getMinutes())}`;

    // Already sent during this server session
    if (lastSentDate === today) return;

    // Already successfully sent before a server restart
    if (hasSuccessfulEmailReport(today)) {
      lastSentDate = today;
      return;
    }

    // Prevent overlapping email sends
    if (sending) return;

    // Wait until configured send time
    if (hhmm < settings.sendTime) return;

    try {
      sending = true;

      await sendRiskEmailNow();

      lastSentDate = today;

      console.log(
        `Evening operations digest sent for ${today} at ${settings.sendTime}`,
      );
    } catch (error) {
      console.error(
        `Evening operations digest failed: ${error.message}`,
      );
    } finally {
      sending = false;
    }
  };

  const timer = setInterval(checkAndSend, 60 * 1000);

  timer.unref?.();

  // Check immediately when server starts
  checkAndSend();

  return timer;
}